### ISSUE TITLE
Global rounding setting for comparison Decimal objects

### ISSUE THREAD

**Issue by maks-rafalko** [php-decimal/php-decimal#4]
Hi there! Thanks for this awesome project.

We use it in quite a big project, and faced with the following issue.

1. After some calculations, we are saving `new Decimal('1.122336')` to MySQL column `DECIMAL (16, 5)`.

  Since scale is `5` in MySQL, but PHP's decimal object has 6 digits, the value is rounded to `1.12234`

2. Then we fetch this value from MySQL and construct PHP Decimal object again:  `new Decimal($valueFromDb`) which is now not equal to the initial value.

Code to demonstrate the issue:

```php
$originalDecimal = new Decimal('1.122336');

$db->save($originalDecimal); // saves 1.12234 because of DECIMAL (16, 5)

$fromDbDecimal = new Decimal($db->fetch()); // returns 1.12234

var_dump($originalDecimal->equals($fromDbDecimal)); // false, because 1.122336 !== 1.12234
```

Of course, we can round before comparing

```php
...
$fromDbDecimal = new Decimal($db->fetch()); // returns 1.12234

$originalDecimal->round(5)->equals($fromDbDecimal); // true !
```

And it solves the issue.

The questions are: 

1. is it possible to set a global setting to round all values to `X` digits before comparing them, when `->equals()` is used?

2. If no, would you be interested in that feature?

3. Do you have any recommendations/best practices on what to do in this case?

**Comment by rtheunissen** [comment]
> is it possible to set a global setting to round all values to X digits before comparing them, when `equals()` is used

There is no way to achieve this, and I believe for good reason. For this case, the decimal is not misbehaving in any way, because you lose data as soon as you round on save. You should round before you call `equals`.

> If no, would you be interested in that feature?

I don't think so. Anything global can affect things unintentionally. 

> Do you have any recommendations/best practices on what to do in this case?

For now, round before you call equals. Abstract it somehow so that it's easy to adjust that when 2.0 is released. There is an abstract `Number` class that you can extend (with operator support) and use in place of `Decimal`, and you can then override `equals` or adjust the way the number is constructed (round on construct, for example). You would use a `Decimal` within the `Number` implementation.

I hope to have a 2.0 beta ready within the next week or two.

**Comment by maks-rafalko** [comment]
Thank you, everything makes sense.
